In [ ]:
import pandas as pd
import torch
import matplotlib.pyplot as plt
import  seaborn as sns
import numpy as np
from torch import nn

In [ ]:
# Data set
from sklearn.datasets import load_breast_cancer
data=load_breast_cancer()
x=data.data
y=data.target
df=pd.DataFrame(x,columns=data.feature_names)
df['target']=y
df['target'].value_counts()

target
1    357
0    212
Name: count, dtype: int64

In [ ]:
# cheaking the data
df.corr()['target']
df.isna().value_counts()
df.head(10)
df.describe()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,0.627417
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,0.483918
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,0.000000
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,0.000000
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,1.000000
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,1.000000
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,1.000000

In [ ]:
# splitting the data
from sklearn.model_selection import train_test_split
X_train,X_test, Y_train, Y_test= train_test_split(x,y,train_size=0.95,random_state=42)

In [ ]:
# Normalize the features
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Re-split data to ensure X_train and X_test are correctly initialized as ndarrays
X_train,X_test, Y_train, Y_test= train_test_split(x,y,train_size=0.95,random_state=42)

scalar = StandardScaler()
X_train=scalar.fit_transform(X_train)
X_test=scalar.transform(X_test)

In [ ]:
# converting to the tensors
X_train=torch.tensor(X_train,dtype=torch.float32)
X_test=torch.tensor(X_test,dtype=torch.float32)
Y_train=torch.tensor(Y_train,dtype=torch.float32)
Y_test=torch.tensor(Y_test,dtype=torch.float32)

In [ ]:
# setting up gpu
device='cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [ ]:
# changing tensor to gpu
X_train=X_train.to(device)
X_test=X_test.to(device)
Y_train=Y_train.to(device)
Y_test=Y_test.to(device)

In [ ]:
# creating the simple model
model=nn.Sequential(
    nn.Linear(in_features=X_train.shape[1],out_features=10),
    nn.ReLU(),
    nn.Linear(in_features=10,out_features=5),
    nn.ReLU(),
    nn.Linear(in_features=5,out_features=2)


)